uploads = []
outputs = []

[[generated]]
id = "d2GDuGIR1FRDgNPI313lP"
uri = "file://src/assets/about_1.png"
type = "image"
title = "generated_image"

[[generated]]
id = "ju0jI0PCBkMDLpB1tFa2Z"
uri = "file://src/assets/about_2.png"
type = "image"
title = "generated_image"

[[generated]]
id = "tlYuFeAvhxUOSr93erCxF"
uri = "file://src/assets/about_3.png"
type = "image"
title = "generated_image"

[[generated]]
id = "n3a8UVI-gvYhK3c-MkHQA"
uri = "file://src/assets/about_4.png"
type = "image"
title = "generated_image"

[[generated]]
id = "d-gAyppF93ZBfuxQ3acT2"
uri = "file://src/assets/guide_4cs.png"
type = "image"
title = "generated_image"

[[generated]]
id = "aX8P--lWJ3cmeT5t4vvCg"
uri = "file://src/assets/guide_labgrown.png"
type = "image"
title = "generated_image"

[[generated]]
id = "pIufY7MPQZc_msKLHVcre"
uri = "file://src/assets/guide_sizing.png"
type = "image"
title = "generated_image"

[[generated]]
id = "gV5yLcwkcm5iWMYSvdRdy"
uri = "file://src/assets/guide_care.png"
type = "image"
title = "generated_image"

[[generated]]
id = "UFNRWjd394p8PFfc1D2Es"
uri = "file://src/assets/guide_certification.png"
type = "image"
title = "generated_image"

[[generated]]
id = "CS64Qivd5PcsOeZh3MUj3"
uri = "file://src/assets/guide_metals.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Gcr1QCXOL9t2mYTmmH9Oe"
uri = "file://src/assets/diamond-hero.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Z0F4Ed7pXFcurZ7fiVAgS"
uri = "file://public/diamonds/round_1.png"
type = "image"
title = "generated_image"

[[generated]]
id = "zlk83p0GMxvEsljCYcbk5"
uri = "file://public/diamonds/round_2.png"
type = "image"
title = "generated_image"

[[generated]]
id = "rer_NVfDNhIJoyw8UAW1E"
uri = "file://public/diamonds/oval_1.png"
type = "image"
title = "generated_image"

[[generated]]
id = "sdk1VPDE4wapSr-bl7D9g"
uri = "file://public/diamonds/princess_1.png"
type = "image"
title = "generated_image"

[[generated]]
id = "FrwndjgWm5042_cTeXmTe"
uri = "file://public/diamonds/cushion_1.png"
type = "image"
title = "generated_image"

[[generated]]
id = "0SZJ1GDc1uY6MTpN2Hsvi"
uri = "file://public/diamonds/emerald_1.png"
type = "image"
title = "generated_image"

[[generated]]
id = "bcC57ilXgqYJRiG_bhjv6"
uri = "file://public/diamonds/pear_1.png"
type = "image"
title = "generated_image"

[[generated]]
id = "mzC9hU5s-2VnPV61BEdCY"
uri = "file://public/diamonds/marquise_1.png"
type = "image"
title = "generated_image"

[[generated]]
id = "srcfHKJzeBl2WApe6vSbl"
uri = "file://public/diamonds/heart_1.png"
type = "image"
title = "generated_image"

[[generated]]
id = "mO4sxwX5O47lmP6T2dvQ5"
uri = "file://public/diamonds/radiant_1.png"
type = "image"
title = "generated_image"
